### ISSUE TITLE
Medium severity vulnerability

### ISSUE THREAD

**Issue by pierre-b** [stephenplusplus/google-auto-auth#2]
@stephenplusplus according to https://snyk.io/test/npm/google-auto-auth , this package should upgrade google-auth-library
Thank you

**Comment by stephenplusplus** [comment]
Thanks for reporting. This has to be fixed through `google-auth-library`: https://github.com/google/google-auth-library-nodejs/pull/86

**Comment by pierre-b** [comment]
Thanks ;)
