### ISSUE TITLE
Cannot assign to read only property 'authClient' of [object Object]

### ISSUE THREAD

**Issue by notentered** [stephenplusplus/google-auto-auth#4]
Hello,

After executing index.js#73:
`self.authClient = authClient;`

I receive: Cannot assign to read only property 'authClient' of [object Object]

Removing index.js#11:
`this.authClient = null;`

looks like a working fix (at least for me).

I'm using google-auto-auth as a dependency for gcloud, which is a dependency of parse-server-gcs-adapter. On node 4.4.3.

**Comment by stephenplusplus** [comment]
Are you able to set up a test repository that I can clone to reproduce? I'm not sure if I'm missing something obvious, but I don't understand why `this.authClient = null` made `this.authClient` as read-only. Also unsure why this hasn't been an issue so far-- this code is executed for all users of [`gcloud`](http://gitnpm.com/gcloud).
