### ISSUE TITLE
Invalid JWT Signature

### ISSUE THREAD

**Issue by TachyonRSA** [stephenplusplus/google-auto-auth#49]
Hey @stephenplusplus 

I am hoping you can help me out, I have tried multiple libraries including the official Google API node module but I keep receiving the same error over and over.

I have created a service account with all the possible permissions under my google api console. Everytime I try to get a token I receive the following: 

> invalid_grant: Invalid JWT Signature.

The code I am using to try and get the token is as follows:
   ```
    var googleAuth = require('google-auto-auth');

    var authConfig = {};
    authConfig.keyFilename = './config/keys/CCKey.json';
    authConfig.scopes = 'https://www.googleapis.com/auth/analytics.readonly';

    var auth = googleAuth(authConfig);

    auth.getToken(function (err, token) {
        console.log(err);
    });
```
I am pulling my hair out with this, maybe I am creating the service account incorrectly? I am not sure at this point anymore, any help will be appreciated.

**Comment by stephenplusplus** [comment]
These token/key things can be very frustrating! Let's start from the beginning, when the key is created:

https://console.cloud.google.com/iam-admin/serviceaccounts/project
---
![image](https://user-images.githubusercontent.com/723048/37655536-055679bc-2c1c-11e8-988d-c23b3e2854fa.png)
---
![image](https://user-images.githubusercontent.com/723048/37655640-44c30df4-2c1c-11e8-893e-aea53c905cec.png)

Clicking "Create" will download the key file that we accept

**Comment by TachyonRSA** [comment]
Hi @stephenplusplus 

I gave that a try, still getting the same error. Have tried different combinations of roles to no avail.

**Comment by stephenplusplus** [comment]
Could you show the code that doesn't work, so I can understand better?

**Comment by TachyonRSA** [comment]
@stephenplusplus 
Sure thing, even when the calling code is in my app.js, if the user logs in then out and tries to get the token again it fails. But, this happens if the user logs in and out on one browser and I try to get the token by visiting the page in another browser as well, so it can't be something to do with the cookies, specific user or the browser.

I tried stepping through the code to find the issue but I can't seem to find it. I couldn't see a difference in the requests once the user has logged out. 

I have now changed the code to directly use the email and private key instead of the JSON file, but the interesting thing is, when I run the code on my linux VPS I get a different error, even with the key and email. The error on my Windows machine stays the same.

The error I receive there is as follows:

> Bad input string

But this error also only happens once a token has been generated, the user logging in then the user logging out and trying to get another token. As I mentioned above, once the user is logged out on one browser, the token cannot be generated from a different browser either.

As you can see below I try to generate the token when the user visits a specific route in my app, but the error still appears when I try it in my app.js file. When the calling code is in the app.js file, I can repeatedly refresh the page and it successfully gets a token every single time, until I log in and then try. I'm not sure if passport.js is interfering with the process in some way, but I am completely lost now, I have no idea what to try anymore. 

Anyways, here is the code that I am using, maybe you can spot something wrong in it.
**Getting the auth token:**
```
function getGToken() {
    var googleAuth = require('google-auto-auth');
    var models = require('./models');
    var serverlog = models.ServerLog;
    var config = models.Config;

    var authConfig = {};
    authConfig.credentials = {
        client_email: 'XXXXX@XXXX.iam.gserviceaccount.com',
        private_key: '-----BEGIN PRIVATE KEY-----\nXXXXXXX==\n-----END PRIVATE KEY-----\n'
    };
    authConfig.scopes = 'https://www.googleapis.com/auth/analytics.readonly';

    var auth = googleAuth(authConfig);

    auth.getToken(function (err, token) {
        if (err) {
            var newServerLog = new serverlog();
            newServerLog.class = 'GToken';
            newServerLog.exception = err.message;
            newServerLog.save();
        } else {
            config.findOne({ where: { key: 'GToken' } }).then((result) => {
                if (result) {
                    result.value = token;
                    result.save();
                } else {
                    var newConfig = new config();
                    newConfig.key = 'GToken';
                    newConfig.value = token;
                    newConfig.save();
                }
            })
        }
    });
}
```

**The calling code:**
```
module.exports = function(app, passport) {
    //LOGIN GET
    app.get('/login', function(req, res) {
        getGToken();
        res.render('login', {
            title: 'Car Centered - Login',
            description: 'Login page for the car centered leads portal.'
        });
    });
   //LOGOUT
    app.get('/logout', function(req, res) {
        req.logout();
        res.redirect('/');
    });
};
```

**Passport login code:**
```
passport.use('login', new LocalStrategy({
        usernameField: 'email',
        passwordField: 'password',
        passReqToCallback: true
    }, function(req, email, password, done) {
        User.findOne({
            where: {
                email: email
            }
        }).then(function(user) {
            if(!user)
                return done(null, false, req.flash('error', 'No user found.'));

            user.validPassword(password).then((correctPass) => {
                if(!correctPass) {
                    return done(null, false, req.flash('error', 'Oops! Wrong password.'));
                } else {
                    user.lastIP = req.connection.remoteAddress;
                    user.save().then(() =>{
                        return done(null, user);
                    });
                }
            });
        });
    }));
```

**App.js trial:**

```
app.use(function (req, res, next) {
    if (!/https/.test(req.protocol)) {
        res.redirect("https://" + req.headers.host + req.url);
    } else {
        getGToken();
        return next();
    }
});
```

**Comment by TachyonRSA** [comment]
@stephenplusplus 
I came right by implementing this functionality using request and the REST api's available from Google.
