### ISSUE TITLE
Make the projectId optional for signing with IAM

### ISSUE THREAD

**Issue by hiranya911** [stephenplusplus/google-auto-auth#53]
The signWithApi method currently requires a `projectId` field:

```
_signWithApi (data, callback) {
    if (!this.projectId) {
      callback(new Error('Cannot sign data without a project ID.'));
      return;
    }
    ...
}
```

However, IAM's [signBlob endpoint](https://cloud.google.com/iam/reference/rest/v1/projects.serviceAccounts/signBlob) can be called without a `projectId` if necessary (using `-` as a wildcard):

```
/projects/-/serviceAccounts/${clientEmail}
```

Can we modify the implementation to default to `-` wildcard when a `projectId` is not given explicitly? This will greatly simplify the usage of the library in some high-level applications, such as [`firebase-admin`](https://github.com/firebase/firebase-admin-node/blob/master/package.json).

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/google/google-auth-library-nodejs/issues/421.
